services:
  - type: web
    name: mi-chatbot-backend
    runtime: python
    plan: starter
    region: ohio
    rootDir: mi_chatbot_ia
    build:
      command: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: TZ
        value: America/Lima
      - fromGroup: chatbot-secrets
    healthCheck:
      path: /
      initialDelaySeconds: 45

postgresql+asyncpg://perseo:zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR@dpg-d2a8hg7diees738on6s0-a:5432/chatbot_db_auqx
postgresql://perseo:zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR@dpg-d2a8hg7diees738on6s0-a/chatbot_db_auqx
postgresql://perseo:zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR@dpg-d2a8hg7diees738on6s0-a.ohio-postgres.render.com/chatbot_db_auqx
PGPASSWORD=zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR psql -h dpg-d2a8hg7diees738on6s0-a.ohio-postgres.render.com -U perseo chatbot_db_auqx

dpg-d2a8hg7diees738on6s0-a
perseo
zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR



postgresql://perseo:zcR32kQZwsZIX7vXg5GoYlE9eNCJ3mzR@dpg-d2a8hg7diees738on6s0-a.ohio-postgres.render.com/chatbot_db_auqx