services:
  - type: web
    name: mi-chatbot-backend
    runtime: python
    plan: starter
    region: ohio
    rootDir: mi_chatbot_ia
    build:
      command: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: TZ
        value: America/Lima
      - fromGroup: chatbot-secrets
    healthCheck:
      path: /
      initialDelaySeconds: 45