version: "1"

services:
  - type: web
    name: mi-chatbot-backend
    runtime: docker
    repo: https://github.com/PromarkSanchez/proyecto1
    plan: standard
    region: ohio
    dockerfilePath: ./mi_chatbot_ia
    autoDeploy: yes
    domains:
      - chatbot.atiqtec.com
    envVars:
      - key: DATABASE_CRUD_URL
        sync: false
      - key: DATABASE_VECTOR_URL
        sync: false
      - key: SYNC_DATABASE_CRUD_URL
        sync: false
      - key: SYNC_DATABASE_VECTOR_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DB_ENCRYPTION_KEY
        sync: false
      - key: FERNET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: AD_SERVER_URL
        sync: false
      - key: AD_BASE_DN
        sync: false
      - key: REDIS_URL
        sync: false