/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ApiClientWithPlainKeyResponseDescription } from './apiClientWithPlainKeyResponseDescription';
import type { ApiClientSettingsSchema } from './apiClientSettingsSchema';
import type { ContextDefinitionBriefForApiClient } from './contextDefinitionBriefForApiClient';
import type { ApiClientWithPlainKeyResponseWebchatUiConfig } from './apiClientWithPlainKeyResponseWebchatUiConfig';
import type { ApiClientWithPlainKeyResponseApiKeyPlain } from './apiClientWithPlainKeyResponseApiKeyPlain';

export interface ApiClientWithPlainKeyResponse {
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: ApiClientWithPlainKeyResponseDescription;
  is_active?: boolean;
  settings: ApiClientSettingsSchema;
  id: number;
  created_at: string;
  updated_at: string;
  allowed_contexts_details?: ContextDefinitionBriefForApiClient[];
  webchat_ui_config?: ApiClientWithPlainKeyResponseWebchatUiConfig;
  api_key_plain?: ApiClientWithPlainKeyResponseApiKeyPlain;
}
