/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ApiClientResponseDescription } from './apiClientResponseDescription';
import type { ApiClientSettingsSchema } from './apiClientSettingsSchema';
import type { ContextDefinitionBriefForApiClient } from './contextDefinitionBriefForApiClient';
import type { ApiClientResponseWebchatUiConfig } from './apiClientResponseWebchatUiConfig';

export interface ApiClientResponse {
  /**
   * @minLength 3
   * @maxLength 100
   */
  name: string;
  description?: ApiClientResponseDescription;
  is_active?: boolean;
  settings: ApiClientSettingsSchema;
  id: number;
  created_at: string;
  updated_at: string;
  allowed_contexts_details?: ContextDefinitionBriefForApiClient[];
  webchat_ui_config?: ApiClientResponseWebchatUiConfig;
}
