/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Identificador de la aplicación cliente principal que usará esta API Key (para X-Application-ID header).
 */
export type ApiClientSettingsSchemaApplicationId = string | null;
