/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { AppUserUpdateEmail } from './appUserUpdateEmail';
import type { AppUserUpdateFullName } from './appUserUpdateFullName';
import type { AppUserUpdateIsActiveLocal } from './appUserUpdateIsActiveLocal';
import type { AppUserUpdateRoleIds } from './appUserUpdateRoleIds';

export interface AppUserUpdate {
  email?: AppUserUpdateEmail;
  full_name?: AppUserUpdateFullName;
  is_active_local?: AppUserUpdateIsActiveLocal;
  /** Para actualizar la lista completa de roles asignados. */
  role_ids?: AppUserUpdateRoleIds;
}
