/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { BodyLoginAdminUnificadoApiV1AdminAuthLoginPostGrantType } from './bodyLoginAdminUnificadoApiV1AdminAuthLoginPostGrantType';
import type { BodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientId } from './bodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientId';
import type { BodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientSecret } from './bodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientSecret';

export interface BodyLoginAdminUnificadoApiV1AdminAuthLoginPost {
  grant_type?: BodyLoginAdminUnificadoApiV1AdminAuthLoginPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientId;
  client_secret?: BodyLoginAdminUnificadoApiV1AdminAuthLoginPostClientSecret;
}
