/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostGrantType } from './bodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostGrantType';
import type { BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientId } from './bodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientId';
import type { BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientSecret } from './bodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientSecret';

export interface BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPost {
  grant_type?: BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostGrantType;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientId;
  client_secret?: BodyLoginAdminWithAdAndHandleMfaApiV1AdminAuthLoginPostClientSecret;
}
