/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ChatResponseMetadataDetails } from './chatResponseMetadataDetails';

/**
 * Representa la respuesta que el backend envía de vuelta al frontend.
Renombramos 'dni' a 'session_id' para consistencia.
 */
export interface ChatResponse {
  /** El mismo session_id de la petición, para que el frontend pueda rastrear la conversación. */
  session_id: string;
  original_message: string;
  bot_response: string;
  metadata_details?: ChatResponseMetadataDetails;
}
