/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ChatRequestUserDni } from './chatRequestUserDni';
import type { ChatRequestUserName } from './chatRequestUserName';
import type { ChatRequestMetadata } from './chatRequestMetadata';

/**
 * Representa la petición que envía el frontend al endpoint de chat.
Ahora soporta tanto sesiones públicas como autenticadas.
 */
export interface ChatRequest {
  /**
   * El mensaje o pregunta del usuario.
   * @minLength 1
   */
  message: string;
  /**
   * Identificador único de la sesión de chat.
   * @minLength 8
   * @maxLength 50
   */
  session_id: string;
  /** Indica si la sesión pertenece a un usuario autenticado en el sistema anfitrión (ej. Blackboard). */
  is_authenticated_user?: boolean;
  /** DNI REAL y verificado del usuario si está autenticado. */
  user_dni?: ChatRequestUserDni;
  /** Nombre del usuario, puede ser proporcionado por el frontend en cualquier momento. */
  user_name?: ChatRequestUserName;
  /** Un espacio para metadatos adicionales enviados desde el frontend. */
  metadata?: ChatRequestMetadata;
}
