/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Lista COMPLETA de IDs de Conexiones a BD. Los no incluidos se desasociarán.
 */
export type ContextDefinitionUpdateDbConnectionIds = number[] | null;
