/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type ContextDefinitionResponseProcessingConfigAnyOf = { [key: string]: unknown };
