/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type ContextMainTypePydanticEnum = typeof ContextMainTypePydanticEnum[keyof typeof ContextMainTypePydanticEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContextMainTypePydanticEnum = {
  DOCUMENTAL: 'DOCUMENTAL',
  DATABASE_QUERY: 'DATABASE_QUERY',
  IMAGE_ANALYSIS: 'IMAGE_ANALYSIS',
} as const;
