/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.1.0
 */

export type ContextMainTypeSchema = typeof ContextMainTypeSchema[keyof typeof ContextMainTypeSchema];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContextMainTypeSchema = {
  DOCUMENTAL: 'DOCUMENTAL',
  DATABASE_QUERY: 'DATABASE_QUERY',
} as const;
