/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo LLM por defecto a usar para este contexto (si difiere del global).
 */
export type ContextDefinitionCreateDefaultLlmModel = string | null;
