/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { DatabaseQueryProcessingConfigSchemaOutputDictionaryTableQuery } from './databaseQueryProcessingConfigSchemaOutputDictionaryTableQuery';
import type { DatabaseQueryProcessingConfigSchemaOutputCustomTableDescriptions } from './databaseQueryProcessingConfigSchemaOutputCustomTableDescriptions';
import type { SqlSelectPolicySchemaOutput } from './sqlSelectPolicySchemaOutput';
import type { StoredProcedureToolOutput } from './storedProcedureToolOutput';

export interface DatabaseQueryProcessingConfigSchemaOutput {
  schema_info_type?: string;
  dictionary_table_query?: DatabaseQueryProcessingConfigSchemaOutputDictionaryTableQuery;
  selected_schema_tables_for_llm?: string[];
  custom_table_descriptions?: DatabaseQueryProcessingConfigSchemaOutputCustomTableDescriptions;
  /** @minimum 100 */
  db_schema_chunk_size?: number;
  /** @minimum 0 */
  db_schema_chunk_overlap?: number;
  sql_select_policy?: SqlSelectPolicySchemaOutput;
  /** Lista de SPs/Funciones expuestas como 'Herramientas' al LLM. */
  tools?: StoredProcedureToolOutput[];
}
