/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { DatabaseQueryProcessingConfigSchemaInputDictionaryTableQuery } from './databaseQueryProcessingConfigSchemaInputDictionaryTableQuery';
import type { DatabaseQueryProcessingConfigSchemaInputCustomTableDescriptions } from './databaseQueryProcessingConfigSchemaInputCustomTableDescriptions';
import type { SqlSelectPolicySchemaInput } from './sqlSelectPolicySchemaInput';
import type { StoredProcedureToolInput } from './storedProcedureToolInput';

export interface DatabaseQueryProcessingConfigSchemaInput {
  schema_info_type?: string;
  dictionary_table_query?: DatabaseQueryProcessingConfigSchemaInputDictionaryTableQuery;
  selected_schema_tables_for_llm?: string[];
  custom_table_descriptions?: DatabaseQueryProcessingConfigSchemaInputCustomTableDescriptions;
  /** @minimum 100 */
  db_schema_chunk_size?: number;
  /** @minimum 0 */
  db_schema_chunk_overlap?: number;
  sql_select_policy?: SqlSelectPolicySchemaInput;
  /** Lista de SPs/Funciones expuestas como 'Herramientas' al LLM. */
  tools?: StoredProcedureToolInput[];
}
