/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { DatabaseQueryProcessingConfigSchemaDictionaryTableQuery } from './databaseQueryProcessingConfigSchemaDictionaryTableQuery';
import type { DatabaseQueryProcessingConfigSchemaCustomTableDescriptions } from './databaseQueryProcessingConfigSchemaCustomTableDescriptions';
import type { SqlSelectPolicySchema } from './sqlSelectPolicySchema';

export interface DatabaseQueryProcessingConfigSchema {
  /** Método para obtener el schema de la BD. */
  schema_info_type?: string;
  /** Query para obtener el diccionario de tablas y columnas (si schema_info_type lo requiere). */
  dictionary_table_query?: DatabaseQueryProcessingConfigSchemaDictionaryTableQuery;
  /** Tablas seleccionadas (schema.tabla) para exponer al LLM. */
  selected_schema_tables_for_llm?: string[];
  /** Descripciones personalizadas para tablas (schema.tabla -> descripción). */
  custom_table_descriptions?: DatabaseQueryProcessingConfigSchemaCustomTableDescriptions;
  /**
   * Tamaño de chunk para procesar el schema de la BD.
   * @minimum 100
   */
  db_schema_chunk_size?: number;
  /**
   * Solapamiento entre chunks del schema.
   * @minimum 0
   */
  db_schema_chunk_overlap?: number;
  sql_select_policy?: SqlSelectPolicySchema;
}
