/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type DBTypePydanticEnum = typeof DBTypePydanticEnum[keyof typeof DBTypePydanticEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DBTypePydanticEnum = {
  POSTGRESQL: 'POSTGRESQL',
  SQLSERVER: 'SQLSERVER',
  MYSQL: 'MYSQL',
  ORACLE: 'ORACLE',
} as const;
