/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type DocSourceTypePydanticEnum = typeof DocSourceTypePydanticEnum[keyof typeof DocSourceTypePydanticEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DocSourceTypePydanticEnum = {
  LOCAL_FOLDER: 'LOCAL_FOLDER',
  S3_BUCKET: 'S3_BUCKET',
  AZURE_BLOB: 'AZURE_BLOB',
  WEB_URL_SINGLE: 'WEB_URL_SINGLE',
} as const;
