/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { DocumentalProcessingConfigSchemaRagPrompts } from './documentalProcessingConfigSchemaRagPrompts';

export interface DocumentalProcessingConfigSchema {
  /** @minimum 100 */
  chunk_size?: number;
  /** @minimum 0 */
  chunk_overlap?: number;
  /** Opcional: {'condense_question_template': '...', 'docs_qa_template': '...'} */
  rag_prompts?: DocumentalProcessingConfigSchemaRagPrompts;
}
