/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

/**
 * Configuración para resolver texto de usuario a un código oficial.
 */
export interface EntityResolver {
  /** Tipo de resolvedor. Actualmente, solo 'CATALOG'. */
  type?: string;
  /** El 'tipo_entidad' a buscar en la tabla acad.catalogo_entidades (ej: 'CURSO', 'PERIODO'). */
  entity_type: string;
}
