/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

/**
 * Schema para la respuesta del generador de prompts.
Contiene el conjunto completo de prompts para un agente.
 */
export interface GeneratedPromptSetResponse {
  greeting_prompt: string;
  name_confirmation_prompt: string;
  system_prompt: string;
}
