/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

export interface GeneratedPromptResponse {
  system_prompt: string;
  greeting_prompt: string;
  name_confirmation_prompt: string;
  /** El system prompt robusto y optimizado, generado por el LLM maestro. */
  optimized_prompt: string;
}
