/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

export interface GeneratePromptRequest {
  /**
   * La descripción simple en lenguaje natural del objetivo del agente.
   * @minLength 10
   * @maxLength 5000
   */
  user_description: string;
  /** ID del LLMModelConfig que se usará como 'LLM maestro' para generar el prompt. */
  llm_model_config_id: number;
}
