/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { HumanAgentUpdateFullName } from './humanAgentUpdateFullName';
import type { HumanAgentUpdateEmail } from './humanAgentUpdateEmail';
import type { HumanAgentUpdateTeamsId } from './humanAgentUpdateTeamsId';
import type { HumanAgentUpdateIsAvailable } from './humanAgentUpdateIsAvailable';
import type { HumanAgentUpdateAvailabilityConfigJson } from './humanAgentUpdateAvailabilityConfigJson';
import type { HumanAgentUpdateGroupIds } from './humanAgentUpdateGroupIds';

export interface HumanAgentUpdate {
  full_name?: HumanAgentUpdateFullName;
  email?: HumanAgentUpdateEmail;
  teams_id?: HumanAgentUpdateTeamsId;
  is_available?: HumanAgentUpdateIsAvailable;
  availability_config_json?: HumanAgentUpdateAvailabilityConfigJson;
  group_ids?: HumanAgentUpdateGroupIds;
}
