/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

export type LLMProviderType = typeof LLMProviderType[keyof typeof LLMProviderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LLMProviderType = {
  GOOGLE: 'GOOGLE',
  OPENAI: 'OPENAI',
  AZURE_OPENAI: 'AZURE_OPENAI',
  ANTHROPIC: 'ANTHROPIC',
  HUGGINGFACE_LOCAL: 'HUGGINGFACE_LOCAL',
  OLLAMA: 'OLLAMA',
  CUSTOM: 'CUSTOM',
  BEDROCK: 'BEDROCK',
} as const;
