/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type ModelLLMModelType = typeof ModelLLMModelType[keyof typeof ModelLLMModelType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelLLMModelType = {
  CHAT_COMPLETION: 'CHAT_COMPLETION',
  TEXT_GENERATION: 'TEXT_GENERATION',
  EMBEDDING: 'EMBEDDING',
  IMAGE_ANALYSIS: 'IMAGE_ANALYSIS',
} as const;
