/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un chatbot avanzado con IA, configurable y con gestión de permisos.
 * OpenAPI spec version: 0.2.0
 */

export type ModelLLMProviderType = typeof ModelLLMProviderType[keyof typeof ModelLLMProviderType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelLLMProviderType = {
  GOOGLE: 'GOOGLE',
  OPENAI: 'OPENAI',
  AZURE_OPENAI: 'AZURE_OPENAI',
  ANTHROPIC: 'ANTHROPIC',
  HUGGINGFACE_LOCAL: 'HUGGINGFACE_LOCAL',
  OLLAMA: 'OLLAMA',
  CUSTOM: 'CUSTOM',
} as const;
