/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */

export type ParamTransformType = typeof ParamTransformType[keyof typeof ParamTransformType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParamTransformType = {
  REMOVE_DASHES: 'REMOVE_DASHES',
  TO_UPPER: 'TO_UPPER',
  EXTRACT_NUMBERS: 'EXTRACT_NUMBERS',
} as const;
