/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ContextMainType } from './contextMainType';

export type ReadAllContextDefinitionsParams = {
/**
 * Número de registros a saltar.
 */
skip?: number;
/**
 * Máximo número de registros a devolver.
 */
limit?: number;
/**
 * Filtrar por tipo principal (DOCUMENTAL, DATABASE_QUERY).
 */
main_type?: ContextMainType | null;
/**
 * Filtrar por estado activo (true/false).
 */
is_active?: boolean | null;
};
