/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ContextMainType } from './contextMainType';

export type ReadAllContextDefinitionsEndpointApiV1AdminContextDefinitionsGetParams = {
skip?: number;
limit?: number;
/**
 * Filtrar por tipo principal de contexto.
 */
main_type?: ContextMainType | null;
/**
 * Filtrar por estado activo.
 */
is_active?: boolean | null;
};
