/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { SPParameterClarificationQuestion } from './sPParameterClarificationQuestion';
import type { ParamTransformType } from './paramTransformType';

export interface SPParameter {
  name: string;
  description_for_llm: string;
  is_required?: boolean;
  clarification_question?: SPParameterClarificationQuestion;
  /** Lista de transformaciones a aplicar al valor extraído ANTES de ejecutar la herramienta. */
  transformations?: ParamTransformType[];
}
