/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { SqlTableAccessRuleSchema } from './sqlTableAccessRuleSchema';

export interface SqlSelectPolicySchema {
  /**
   * Límite de filas por defecto para SELECT.
   * @minimum 0
   * @maximum 1000
   */
  default_select_limit?: number;
  /**
   * Límite máximo de filas permitido para SELECT.
   * @minimum 0
   * @maximum 2000
   */
  max_select_limit?: number;
  allow_joins?: boolean;
  allowed_join_types?: string[];
  allow_aggregations?: boolean;
  allowed_aggregation_functions?: string[];
  allow_group_by?: boolean;
  allow_order_by?: boolean;
  allow_where_clauses?: boolean;
  forbidden_keywords_in_where?: string[];
  /** Reglas de acceso a columnas por tabla. */
  column_access_rules?: SqlTableAccessRuleSchema[];
  /** Instrucciones adicionales para el LLM al generar SQL. */
  llm_instructions_for_select?: string[];
}
