/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { SqlSelectPolicySchemaOutputColumnAccessPolicyFromDb } from './sqlSelectPolicySchemaOutputColumnAccessPolicyFromDb';
import type { SqlTableAccessRuleSchema } from './sqlTableAccessRuleSchema';

export interface SqlSelectPolicySchemaOutput {
  /**
   * @minimum 0
   * @maximum 1000
   */
  default_select_limit?: number;
  /**
   * @minimum 0
   * @maximum 2000
   */
  max_select_limit?: number;
  allow_joins?: boolean;
  allowed_join_types?: string[];
  allow_aggregations?: boolean;
  allowed_aggregation_functions?: string[];
  allow_group_by?: boolean;
  allow_order_by?: boolean;
  allow_where_clauses?: boolean;
  forbidden_keywords_in_where?: string[];
  allowed_tables_for_select?: string[];
  column_access_policy_from_db?: SqlSelectPolicySchemaOutputColumnAccessPolicyFromDb;
  column_access_rules?: SqlTableAccessRuleSchema[];
  llm_instructions_for_select?: string[];
}
