/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ToolParameter } from './toolParameter';

/**
 * Define un Stored Procedure o Función de BD como una 'Herramienta' completa.
 */
export interface StoredProcedureToolOutput {
  /** Nombre único y descriptivo para la herramienta (ej: 'obtener_notas_del_alumno'). */
  tool_name: string;
  /** Descripción para que un LLM de alto nivel sepa cuándo podría usarse esta herramienta (funcionalidad futura). */
  description_for_llm: string;
  /** Nombre completo y real del SP o Función en la BD (ej: 'acad.fn_app_obtener_notas_curso'). */
  procedure_name: string;
  /** La lista de todos los parámetros que la herramienta necesita. */
  parameters?: ToolParameter[];
}
