/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { SPParameter } from './sPParameter';

/**
 * Define un Stored Procedure o Función de BD como una 'Herramienta' usable por el LLM.
 */
export interface StoredProcedureToolInput {
  /** Un nombre corto y único para la herramienta (ej: 'obtener_notas_alumno'). */
  tool_name: string;
  /** El nombre real y completo del SP o función en la BD (ej: 'acad.usp_obtener_notas_alumno'). */
  procedure_name: string;
  /** Descripción detallada para que el LLM principal sepa cuándo y para qué elegir esta herramienta. */
  description_for_llm: string;
  /** Lista de parámetros que requiere el SP/función. */
  parameters?: SPParameter[];
}
