/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { EntityResolver } from './entityResolver';

/**
 * Configuración opcional para resolver la entrada del usuario a un código oficial usando el catálogo de entidades.
 */
export type ToolParameterEntityResolver = EntityResolver | null;
