/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { ToolParameterDescriptionForLlm } from './toolParameterDescriptionForLlm';
import type { ToolParameterClarificationQuestion } from './toolParameterClarificationQuestion';
import type { ToolParameterEntityResolver } from './toolParameterEntityResolver';
import type { ParamTransformType } from './paramTransformType';

/**
 * Define un parámetro individual para una herramienta de BD.
 */
export interface ToolParameter {
  /** Nombre del parámetro (ej: p_scurso). Debe coincidir exactamente con el de la BD. */
  name: string;
  /** Descripción en lenguaje natural para que el LLM sepa qué buscar en la conversación. */
  description_for_llm?: ToolParameterDescriptionForLlm;
  /** Indica si este parámetro es obligatorio para ejecutar la herramienta. */
  is_required?: boolean;
  /** Marcar como 'true' si este es el parámetro que debe recibir el DNI del usuario logueado. */
  is_dni_param?: boolean;
  /** Pregunta específica que el bot hará al usuario si este parámetro falta. */
  clarification_question?: ToolParameterClarificationQuestion;
  /** Configuración opcional para resolver la entrada del usuario a un código oficial usando el catálogo de entidades. */
  entity_resolver?: ToolParameterEntityResolver;
  /** Lista de transformaciones de formato a aplicar al valor (ej: quitar guiones). */
  transformations?: ParamTransformType[];
}
