/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { UserCreateEmail } from './userCreateEmail';
import type { UserCreateFullName } from './userCreateFullName';
import type { UserCreateRole } from './userCreateRole';

export interface UserCreate {
  /**
   * DNI del usuario final o ID de sesión.
   * @minLength 8
   * @maxLength 20
   */
  dni: string;
  /** Email opcional del usuario final. */
  email?: UserCreateEmail;
  /** Nombre completo opcional del usuario final. */
  full_name?: UserCreateFullName;
  /** Rol del usuario final para segmentación (ej. 'cliente', 'invitado'). */
  role?: UserCreateRole;
  /** Indica si el usuario final está activo en el sistema. */
  is_active?: boolean;
}
