/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { UserResponseEmail } from './userResponseEmail';
import type { UserResponseFullName } from './userResponseFullName';
import type { UserResponseRole } from './userResponseRole';

export interface UserResponse {
  /**
   * DNI del usuario final o ID de sesión.
   * @minLength 8
   * @maxLength 20
   */
  dni: string;
  /** Email opcional del usuario final. */
  email?: UserResponseEmail;
  /** Nombre completo opcional del usuario final. */
  full_name?: UserResponseFullName;
  /** Rol del usuario final para segmentación (ej. 'cliente', 'invitado'). */
  role?: UserResponseRole;
  id: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
