/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { VirtualAgentProfileCreateDescription } from './virtualAgentProfileCreateDescription';
import type { VirtualAgentProfileCreateUserProvidedGoalDescription } from './virtualAgentProfileCreateUserProvidedGoalDescription';
import type { VirtualAgentProfileCreateSystemPrompt } from './virtualAgentProfileCreateSystemPrompt';
import type { VirtualAgentProfileCreateGreetingPrompt } from './virtualAgentProfileCreateGreetingPrompt';
import type { VirtualAgentProfileCreateNameConfirmationPrompt } from './virtualAgentProfileCreateNameConfirmationPrompt';
import type { VirtualAgentProfileCreateTemperatureOverride } from './virtualAgentProfileCreateTemperatureOverride';
import type { VirtualAgentProfileCreateMaxTokensOverride } from './virtualAgentProfileCreateMaxTokensOverride';
import type { VirtualAgentProfileCreateCharacterSheetJson } from './virtualAgentProfileCreateCharacterSheetJson';

export interface VirtualAgentProfileCreate {
  name: string;
  description?: VirtualAgentProfileCreateDescription;
  user_provided_goal_description?: VirtualAgentProfileCreateUserProvidedGoalDescription;
  system_prompt?: VirtualAgentProfileCreateSystemPrompt;
  greeting_prompt?: VirtualAgentProfileCreateGreetingPrompt;
  name_confirmation_prompt?: VirtualAgentProfileCreateNameConfirmationPrompt;
  llm_model_config_id: number;
  temperature_override?: VirtualAgentProfileCreateTemperatureOverride;
  max_tokens_override?: VirtualAgentProfileCreateMaxTokensOverride;
  is_active?: boolean;
  character_sheet_json?: VirtualAgentProfileCreateCharacterSheetJson;
}
