/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { VirtualAgentProfileResponseDescription } from './virtualAgentProfileResponseDescription';
import type { VirtualAgentProfileResponseUserProvidedGoalDescription } from './virtualAgentProfileResponseUserProvidedGoalDescription';
import type { VirtualAgentProfileResponseGreetingPrompt } from './virtualAgentProfileResponseGreetingPrompt';
import type { VirtualAgentProfileResponseNameConfirmationPrompt } from './virtualAgentProfileResponseNameConfirmationPrompt';
import type { VirtualAgentProfileResponseTemperatureOverride } from './virtualAgentProfileResponseTemperatureOverride';
import type { VirtualAgentProfileResponseMaxTokensOverride } from './virtualAgentProfileResponseMaxTokensOverride';
import type { VirtualAgentProfileResponseDefaultUserRole } from './virtualAgentProfileResponseDefaultUserRole';
import type { VirtualAgentProfileResponseFallbackPrompt } from './virtualAgentProfileResponseFallbackPrompt';
import type { VirtualAgentProfileResponseLlmModelConfig } from './virtualAgentProfileResponseLlmModelConfig';
import type { VirtualAgentProfileResponseCharacterSheetJson } from './virtualAgentProfileResponseCharacterSheetJson';

export interface VirtualAgentProfileResponse {
  /**
   * @minLength 3
   * @maxLength 150
   */
  name: string;
  description?: VirtualAgentProfileResponseDescription;
  user_provided_goal_description?: VirtualAgentProfileResponseUserProvidedGoalDescription;
  /** @minLength 1 */
  system_prompt: string;
  greeting_prompt?: VirtualAgentProfileResponseGreetingPrompt;
  name_confirmation_prompt?: VirtualAgentProfileResponseNameConfirmationPrompt;
  llm_model_config_id: number;
  temperature_override?: VirtualAgentProfileResponseTemperatureOverride;
  max_tokens_override?: VirtualAgentProfileResponseMaxTokensOverride;
  is_active?: boolean;
  default_user_role?: VirtualAgentProfileResponseDefaultUserRole;
  fallback_prompt?: VirtualAgentProfileResponseFallbackPrompt;
  id: number;
  llm_model_config?: VirtualAgentProfileResponseLlmModelConfig;
  character_sheet_json?: VirtualAgentProfileResponseCharacterSheetJson;
  created_at: string;
  updated_at: string;
}
