/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Mi Chatbot IA Personalizable
 * Un backend API en Python (FastAPI) para un chatbot avanzado con IA, configurable, capaz de conectarse a diversas fuentes de contexto y con gestión de permisos para administradores.
 * OpenAPI spec version: 0.2.0
 */
import type { VirtualAgentProfileUpdateName } from './virtualAgentProfileUpdateName';
import type { VirtualAgentProfileUpdateDescription } from './virtualAgentProfileUpdateDescription';
import type { VirtualAgentProfileUpdateUserProvidedGoalDescription } from './virtualAgentProfileUpdateUserProvidedGoalDescription';
import type { VirtualAgentProfileUpdateSystemPrompt } from './virtualAgentProfileUpdateSystemPrompt';
import type { VirtualAgentProfileUpdateGreetingPrompt } from './virtualAgentProfileUpdateGreetingPrompt';
import type { VirtualAgentProfileUpdateNameConfirmationPrompt } from './virtualAgentProfileUpdateNameConfirmationPrompt';
import type { VirtualAgentProfileUpdateCharacterSheetJson } from './virtualAgentProfileUpdateCharacterSheetJson';
import type { VirtualAgentProfileUpdateLlmModelConfigId } from './virtualAgentProfileUpdateLlmModelConfigId';
import type { VirtualAgentProfileUpdateTemperatureOverride } from './virtualAgentProfileUpdateTemperatureOverride';
import type { VirtualAgentProfileUpdateMaxTokensOverride } from './virtualAgentProfileUpdateMaxTokensOverride';
import type { VirtualAgentProfileUpdateIsActive } from './virtualAgentProfileUpdateIsActive';
import type { VirtualAgentProfileUpdateDefaultUserRole } from './virtualAgentProfileUpdateDefaultUserRole';
import type { VirtualAgentProfileUpdateFallbackPrompt } from './virtualAgentProfileUpdateFallbackPrompt';

export interface VirtualAgentProfileUpdate {
  name?: VirtualAgentProfileUpdateName;
  description?: VirtualAgentProfileUpdateDescription;
  user_provided_goal_description?: VirtualAgentProfileUpdateUserProvidedGoalDescription;
  system_prompt?: VirtualAgentProfileUpdateSystemPrompt;
  greeting_prompt?: VirtualAgentProfileUpdateGreetingPrompt;
  name_confirmation_prompt?: VirtualAgentProfileUpdateNameConfirmationPrompt;
  character_sheet_json?: VirtualAgentProfileUpdateCharacterSheetJson;
  llm_model_config_id?: VirtualAgentProfileUpdateLlmModelConfigId;
  temperature_override?: VirtualAgentProfileUpdateTemperatureOverride;
  max_tokens_override?: VirtualAgentProfileUpdateMaxTokensOverride;
  is_active?: VirtualAgentProfileUpdateIsActive;
  default_user_role?: VirtualAgentProfileUpdateDefaultUserRole;
  fallback_prompt?: VirtualAgentProfileUpdateFallbackPrompt;
}
